services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    restart: unless-stopped
    networks:
      - effective_network

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - effective_network

networks:
  effective_network:
    driver: bridge
